prettier/prettier-atom

package.json

Nothing big, just did it for myself and thought maybe I could save you a few seconds with this.
I am very excited about the whole thing!
Cheers!

Bump version and dependency to 0.0.4

---

README.md

Updates a reference from standard-formatter to prettier

Update Menu path in readme

---

lib/helpers.js
lib/prettier.js
package.json

Specify Scopes for Format on Save

---

package.json

I don't know if there's something more needed here. Based on what I saw from the history of recent updates this was all that was done.

Bump version to 0.15.0

---

package.json

Update to 0.16.0

---

dist/main.js
src/main.js

Because formatOnSave was being called by an event listener that was nested inside of another event
listener, only the outside event listener was getting tracked (and disposed) by CompositeDisposable.
Now, we make sure to add the inner event listener to the CompositeDisposable.
Fixes #84

fix(formatOnSave): do not format on save after plugin is disabled

---

package.json
yarn.lock

Just a small change to the defaults. Nothing breaking for you :)

chore(deps): upgrade to prettier-eslint@6

---

src/config-schema.json

Fixes https://github.com/prettier/prettier-atom/issues/144.

Tweak the checkbox name to be more prominent

---

package-scripts.yml
yarn.lock

I keep forgetting to build my sources, so I wanted to add this.
Also updating `yarn.lock` which was missing dependencies that were added recently.

Add build.watch task and update yarn.lock

---

dist/config-schema.json
dist/main.js
src/config-schema.json
src/helpers.js
src/main.js
src/options.js
src/options.test.js

Add an option to show/hide formatOnSave's state in the status bar

---

dist/config-schema.json
dist/options.js
src/__snapshots__/options.test.js.snap
src/config-schema.json
src/options.js
src/options.test.js
src/warnAboutLinterEslintFixOnSave.test.js

Add editorconfig option which allows user to enable/disable editorconfig integration

feat(options): add editorconfig option to package settings

---

dist/statusTile.js
src/statusTile.js
src/statusTile.test.js

Added a click listener to toggle the formatOnSave option via the status indicator.

feat(statusBar): Added click handler to toggle formatOnSave

---

decls/index.js
dist/atomInterface/index.js
dist/warnAboutLinterEslintFixOnSave/index.js
src/atomInterface/index.js
src/warnAboutLinterEslintFixOnSave/index.js
src/warnAboutLinterEslintFixOnSave/index.test.js

fix(warnings): Check if linter-eslint is actually active instead of reading user config

---

dist/config-schema.json
src/config-schema.json

Fixes #195
Also made some changes in the package settings: fixed some typos and tried to clarify some descriptions (see comments in #195).

feat(css): Add LESS and SCSS to default scopes for CSS files

---

dist/statusTile/updateStatusTileScope.js
src/statusTile/updateStatusTileScope.js
src/statusTile/updateStatusTileScope.test.js

Also added a test for this case.

refactor(statusTile): Pass Maybe type for case where TextEditor is undefined

---

dist/config-schema.json
src/config-schema.json

The description was backward. Now the description will correctly reflect the actual behavior.
Resolves #209

docs(config-schema): fix description for isDisabledIfNotInPackageJson

---

dist/executePrettier/buildPrettierOptions.js
src/executePrettier/buildPrettierOptions.js

fix(prettierOptions): Always disable trailingComma option for JSON

---

dist/atomInterface/index.js
dist/config-schema.json
dist/editorInterface/index.js
dist/executePrettier/buildPrettierOptions.js
src/atomInterface/index.js
src/config-schema.json
src/editorInterface/index.js
src/editorInterface/index.test.js
src/executePrettier/buildPrettierOptions.js
src/executePrettier/buildPrettierOptions.test.js

feat(graphql): add GraphQl query support (requires language-graphql)

---

dist/atomInterface/index.js
dist/config-schema.json
dist/executePrettier/buildPrettierStylelintOptions.js
dist/executePrettier/executePrettierOnBufferRange.js
package.json
src/atomInterface/index.js
src/atomInterface/index.test.js
src/config-schema.json
src/executePrettier/buildPrettierStylelintOptions.js
src/executePrettier/buildPrettierStylelintOptions.test.js
src/executePrettier/executePrettierOnBufferRange.js
src/executePrettier/executePrettierOnBufferRange.test.js
yarn.lock

fix #288 
This PR adds support for [prettier-stylelint](https://github.com/hugomrdias/prettier-stylelint).
Let me know if there is anything that needs to change =D

feat(prettier-stylelint): Add support for prettier-stylelint

---

dist/executePrettier/executePrettierOnBufferRange.js

fix(manual-format): fix bug from forgetting to rebuild dist

---

src/atomInterface/__snapshots__/index.test.js.snap
src/atomInterface/index.test.js

Fix test on getPrettierOptions() and corresponding snapshot

---

dist/atomInterface/index.js
dist/config-schema.json
dist/editorInterface/index.js
dist/executePrettier/buildPrettierOptions.js
package.json
src/atomInterface/index.js
src/config-schema.json
src/editorInterface/index.js
src/editorInterface/index.test.js
src/executePrettier/buildPrettierOptions.js
src/executePrettier/buildPrettierOptions.test.js
yarn.lock

Closes #327.
Removed Vue from embedded script targets and added dedicated scope in settings.

Vue SFC support

---

package.json
yarn.lock

feat(prettier-eslint): bump to 8.7.6

---

dist/formatOnSave/isPrettierInPackageJson.js
dist/formatOnSave/isPrettierInPackageJson.test.js
src/formatOnSave/isPrettierInPackageJson.js
src/formatOnSave/isPrettierInPackageJson.test.js

fix(deps): correctly use new pkg-up, fixup f5a0b18, #507

---

dist/displayDebugInfo/index.js
dist/displayDebugInfo/index.test.js
dist/formatOnSave/isPrettierInPackageJson.test.js
src/displayDebugInfo/index.js
src/displayDebugInfo/index.test.js

fix(debug): fix error with debug due to change in readPgkUp API

---

.github/workflows/eslint.yml

We are migrating to GitHub actions instead of TravisCI.

ci(github-actions): add ESLint GitHub action
