prettier/prettier-atom

- lib/prettier.js
Exposes the [core prettier api options](https://github.com/jlongster/prettier#api) as configuration options in the Atom package.
Fixes #4
> Expose all core prettier options in Atom config

- lib/helpers.js
The unsupported file type warning doesn't seem necessary, especially if format-on-save is enabled. It's understood that prettier formats JS code, so seeing the unsupported file type warning while editing non-JS code isn't that helpful. It gets a bit spammy.
> Remove unsupported file type warning

- lib/helpers.js
Fixes #27 
When opening a new blank document, there is no current path since the user hasn't saved the document to the hard disk yet, so `atom.workspace.getActiveTextEditor().getPath()` can return undefined. Therefore, if the user manually calls prettier via the ctrl+alt+f command and no text is selected, we will try to check that the path is supported, and it will hard error.
This fixes that by just assuming that since the user must be calling the command for this to be the case, that we should go ahead and attempt to do the transform.
> Fix error due to editor.getPath() returning undefined

- lib/helpers.js
- package.json
For JS embedded within a `<script>` tag in .html or .vue files, selecting the text and transforming currently works well, but it would be nice if this were easier. I've added `text.html.basic` and `text.html.vue` to the allowed scopes, and for these scopes, added the ability to transform the text only within the `<script>` tag.
> add ability to transform js embedded in .html or .vue files

- lib/helpers.js
- package.json
Continuation of #45 
Please review the code. I'm sure you might want to solve this problem differently
> new option: "Silent error on save"

- lib/helpers.js
- package.json
Changes "useFlowParser" to "parser" (now a string enum), and adds "jsxBracketSameLine".
> Update to use proper options for 0.17.1 of Prettier

- lib/helpers.js
Hey, I've little mess up with #46 
This is a bug fix
> BUG FIX: `formatOnSaveSilentError` option is opposite for what it supposed to be

- package.json
Updates Prettier dep to 0.19.0, and changes trailingComma option to enum.
> Update to Prettier 0.19.0

- dist/helpers.js
- dist/main.js
- dist/warnAboutLinterEslintFixOnSave.js
- src/helpers.js
- src/helpers.test.js
- src/main.js
- src/warnAboutLinterEslintFixOnSave.js
- src/warnAboutLinterEslintFixOnSave.test.js
If linter-eslint's "Format On Save" feature is enabled at the same time as prettier-atom's ESlint
integration is on, it will be somewhat redundant and may cause errors. Therefore, we warn the user
if both of these options are detected to be on at the same time.
> feat($linter-eslint): Warn about linter-eslint "Format on Save"

- decls/index.js
- dist/formatOnSave.js
- src/formatOnSave.js
- src/formatOnSave.test.js
- src/helpers.js
There may be cases where an editor will return a null filePath (such as when saving a new file).
Previously, doing so would cause an error because we assumed its presence when looking for the
nearest `.eslintignore` file. The solution is to short-circuit this check if the filePath is not
present, since there's no way it can be ignored if it doesn't have a path anyway.
Fixes #67
> fix($formatOnSave): Handle null filePath

- dist/helpers.js
- src/helpers.js
- src/helpers.test.js
We were not properly handling the case where no `.eslintignore` was found when attempting to
determine whether to run `formatOnSave`. Now, if no `.eslintignore` is found, we short circuit and
assume the file is not ignored.
Fixes #67 (again)
> fix($formatOnSave): Fix error when no .eslintignore is found

- dist/formatOnSave.js
- dist/helpers.js
- src/formatOnSave.js
- src/formatOnSave.test.js
- src/helpers.js
- src/helpers.test.js
During the integration of `prettier-eslint`, somehow the excludedGlobs option never got implemented
in formatOnSave. This has now been added back in.
Fixes #73
> fix(excludedGlobs): Respect excluded globs when formatting on save

- dist/main.js
- src/main.js
It seems that Atom may have a bug that is causing errors for some users. When we moved to a new
config schema, some users still have the old configuration options still set. This is preventing
them from loading prettier in some cases, because the options have incorrect values. It's difficult
to tell what is going on here and this fix may not work.
Fixes #72
> fix($config): Unset old config options causing errors

- CHANGELOG.md
- dist/main.js
Add an auto-generated changelog using the conventional-changelog CLI. The command that was run is
`conventional-changelog -p angular -i CHANGELOG.md -s -r 0`.
Closes #28
> docs($changelog): Add CHANGELOG.md using conventional-changelog angular

- decls/index.js
- dist/helpers.js
- src/helpers.js
- src/helpers.test.js
Fixes a bug where saving a brand new file would cause an error. This was because we were trying to
access the path of the editor's buffer's file when the file is actually null. Now we check for the
presence of the file before trying to access its path.
Fixes #79
> fix(formatOnSave): don't error when saving a new file

- dist/config-schema.json
- dist/formatOnSave.js
- dist/helpers.js
- src/config-schema.json
- src/formatOnSave.js
- src/formatOnSave.test.js
- src/helpers.js
- src/helpers.test.js
Whitelist globs will take precedence over any scopes and excluded globs. For more information on how
globs are matched, see the documentation at https://github.com/isaacs/minimatch. We are not using
any special options from the minimatch library.
Closes #62
> feat(whitelist-globs): add ability to whitelist globs

- package.json
Just to make sure it's clear that prettier-eslint is optional.
> docs(package): clarify description

- dist/config-schema.json
- dist/formatOnSave.js
- dist/helpers.js
- src/config-schema.json
- src/formatOnSave.js
- src/formatOnSave.test.js
- src/helpers.js
- src/helpers.test.js
**What**: Update the logic of whitelist to be required if provided
**Why**: The use case of a whitelist is for people who have various projects on their machine. Some of them they are able to use `prettier-atom` on and others they are not. It's often easier to maintain a list of projects they're allowed to use `prettier-atom` on (whitelist) than it is to maintain a list of projects they are _not_ allowed to use `prettier-atom` on (blacklist). For these users, we say that if you do provide a whitelist, then the files _must_ match the whitelist or they will _not_ be formatted on save.
**How**:
- Add method `isWhitelistProvided` to `helpers`
- Add logic in `formatOnSaveIfAppropriate` for skipping if the whitelist is provided and the file is not whitelisted
- Add note in config schema about …
> feat(whitelist): force whitelist if provided

- decls/index.js
- dist/executePrettier.js
- dist/helpers.js
- src/executePrettier.js
- src/executePrettier.test.js
- src/helpers.js
- src/helpers.test.js
Formatting seemed to cause linter highlighting to disappear. Now, if we detect that the
`linter:lint` command exists, we invoke it after formatting so that the highlighting will reappear.
Fixes #86
> fix(linter): refresh linter highlighting after format

- dist/executePrettier.js
- src/executePrettier.js
- src/executePrettier.test.js
This PR brings two improvements, it:
- removes unnecessary glitches that happen when the content of the editor is overwritten
- preserves the history, since it removes unnecessary text buffer changes
> fix(prettier): Don't alter text buffer if file is already pretty

- dist/executePrettier.js
- src/executePrettier.js
This PR shortens the error notification while keeping the option to show the whole stack trace.
**Proposed:**
**master:**
Fixes #49
> feat(error): Cleanup error notification

- menus/prettier-js.json
This time, with commitizen.
Context menus didn't include the `Format` action for files that use `Babel` or `JavaScript with JSX` for syntax highlight (from the `language-babel` package).
> Enable context menu entry for JSX files

- .github/ISSUE_TEMPLATE.md
We are getting many issues that actually should have been posted on prettier or prettier-eslint.
Hopefully this should head some of those issues off before they get created.
> docs(issue-template): add message about prettier and prettier-eslint repos

- .eslintrc.yml
- decls/index.js
- dist/helpers.js
- dist/main.js
- dist/statusTile.js
- dist/toggleFormatOnSave.js
- menus/prettier-js.json
- package.json
- src/displayDebugInfo.js
- src/helpers.js
- src/main.js
- src/statusTile.js
- src/statusTile.test.js
- src/toggleFormatOnSave.js
- src/toggleFormatOnSave.test.js
- styles/statusTile.css
Fixes https://github.com/prettier/prettier-atom/issues/117.
The new command is defined as `prettier:toggle-format-on-save`.
I also wanted to add a visual indicator for the command, because it's not practical when you don't know if the option is already enabled or not.
I tried to make something in the status bar with Prettier's logo, but it looked terrible with small dimensions and it didn't fit with the other tiles.
I ended up just adding a "Prettier" label:
<details>
**Enabled**
**Disabled**
</details>
> Toggle command for "Format on Save" option

- dist/config-schema.json
- dist/executePrettier.js
- src/config-schema.json
- src/executePrettier.js
- src/executePrettier.test.js
Previously, if we couldn't infer a prettier setting from a user's eslint config, we fell back to
default prettier settings. Now, we take advantage of a new prettier-eslint feature that let's us
provide fallback options to use instead of the prettier defaults. This means that if you don't have
a semicolons rule in your eslint config, we will use the semicolon rule from your prettier-atom
settings.
> feat(eslint-fallbacks): fallback to user's prettier settings if cannot be inferred from eslint confi

- dist/displayDebugInfo/index.js
- src/displayDebugInfo/index.js
Providing a relative path would mean depending on current working directory which could change on
different environments. This ensures we target the correct directory.
Fixes #156
> fix(debugCommand): Provide package's absolute path to read package.json

- dist/atomInterface/index.js
- dist/config-schema.json
- dist/editorInterface/index.js
- dist/executePrettier/buildPrettierOptions.js
- dist/formatOnSave/shouldFormatOnSave.js
- src/atomInterface/index.js
- src/config-schema.json
- src/editorInterface/index.js
- src/editorInterface/index.test.js
- src/executePrettier/buildPrettierOptions.js
- src/executePrettier/buildPrettierOptions.test.js
- src/formatOnSave/shouldFormatOnSave.js
- src/formatOnSave/shouldFormatOnSave.test.js
We now allow adding scopes (some defaults have already been provided for you) for typescript and
CSS. If we recognize the text you are trying to format as being one of these scopes, we will
automatically use the appropriate parser.
Resolves #183 
Resolves #184
> feat(parsers): add typescript and CSS support

- dist/main.js
- src/main.js
We fetched the active text editor on every save, which prevented formatting all saved files.
Fixes #96
> fix(save): On save, use editor provided by observer

- CHANGELOG.md
The wrong version was mentioned due to a typo in 499516f.
> docs(changelog): fix prettier version in 0.32.0

- dist/main.js
- dist/statusTile/createStatusTile.js
- dist/statusTile/index.js
- dist/statusTile/updateStatusTile.js
- dist/statusTile/updateStatusTileScope.js
- src/main.js
- src/statusTile/createStatusTile.js
- src/statusTile/createStatusTile.test.js
- src/statusTile/index.js
- src/statusTile/updateStatusTile.js
- src/statusTile/updateStatusTile.test.js
- src/statusTile/updateStatusTileScope.js
- src/statusTile/updateStatusTileScope.test.js
- styles/statusTile.css
- styles/statusTile.less
Fixes #170 
Also updated the tooltip to show the user can click on it to toggle `Format on Save`.
PS: My commit messages were truncated for some reason 😒
> feat(statusTile): Display status bar tile only if active file matches one of the scopes in settings

- dist/main.js
- src/main.js
`onDidChangeActiveTextEditor` is available on Atom 1.18.0+ only. This avoids throwing errors for users
that are still using old versions of Atom.
Fixes #205
> fix(main): Subscribe to onDidChangeActivePaneItem when onDidChangeActiveTextEditor is not available

- src/executePrettier/buildPrettierOptions.test.js
Our json scope test will now check for disabling of trailing commas, as prettier erroneously adds
trailing commas in JSON files otherwise.
> test(buildPrettierOptions): fix json scope test

- dist/displayDebugInfo/index.js
- src/displayDebugInfo/index.js
- src/displayDebugInfo/index.test.js
read-pkg and read-pkg-up do not have the same API.
Fixes #217
> fix(debug): Fix usage of readPkgUp to fetch package info

- dist/atomInterface/index.js
- dist/formatOnSave/index.js
- src/atomInterface/index.js
- src/formatOnSave/index.js
- src/formatOnSave/index.test.js
In unexpected situations where errors other than parsing errors during formatting are raised (the
latter already being handled), users are unable to save without disabling prettier because the Error
prevents the save from executing. Now we will wrap the logic inside of `formatOnSave` with a
try/catch that will catch this error and show a notification. This will inform the user that an
error occurred, but won't prevent saving their file.
Resolves #190
> fix(formatOnSave): don't prevent user from saving if uncaught error

- decls/index.js
- dist/executePrettier/handleError.js
- src/executePrettier/handleError.js
- src/executePrettier/handleError.test.js
Prettier sometimes provides a different API for the `loc` property on the errors it throws. We were
only anticipating one type, where there is a `start` property nested in `loc`, but there's actually
another where the line and column are direct children of `loc` and there is no `start` property. We
now will properly handle either case.
Fixes #229
> fix(handleError): properly handle alternative loc in Prettier errors

- decls/index.js
- dist/executePrettier/handleError.js
- src/executePrettier/handleError.js
- src/executePrettier/handleError.test.js
Previously, we were assuming all errors thrown during execution of the formatters were going to be
syntax errors. However, this is not the case, so we must handle these errors elegantly by displaying
them in a popup.
Resolves #231
> fix(errors): handle errors that aren't syntax errors

- styles/statusTile.less
Style was previously applied to every div in Atom.
@robwise Sorry for bailing out lately! I was a bit overwhelmed at work and didn't want to do more of the same at home.
I'm back to reading issues and trying to get up to speed though!
> fix(statusTile): Fix style scope

- dist/executePrettier/handleError.js
- src/executePrettier/handleError.js
- src/executePrettier/handleError.test.js
Previously we were simply exiting early during the error handling process if there was no filepath
because the linter package requires a filepath in order to work. Now, we detect this early and
instead send the error message to a popup so that the user still gets some feedback.
See: https://github.com/steelbrain/linter/issues/1235
Fixes #235
> fix(display-of-errors): show syntax errors for unsaved files

- dist/atomInterface/index.js
- dist/executePrettier/handleError.js
- dist/linterInterface/index.js
- dist/main.js
- src/atomInterface/index.js
- src/executePrettier/handleError.js
- src/executePrettier/handleError.test.js
- src/formatOnSave/index.test.js
- src/linterInterface/index.js
We were either using the linter package or an in-app popup to display errors, but now we also will
log the error to the console for closer inspection.
> feat(error-logging): log errors to Atom's developer tools

- README.md
- dist/config-schema.json
- src/config-schema.json
Fixes #241.
It was actually simpler than I thought, because Atom's JSON schema can accept multiple types for one setting and it handles priority.
> Fix tabWidth setting type

- src/config-schema.json
Postcss is a popular and common css processor/syntax, this change makes it such that prettier-atom lints postcss files by default :sparkles:
Ref #183
> Process postcss files!

- src/executePrettier/executePrettierOnBufferRange.js
- src/executePrettier/executePrettierOnBufferRange.test.js
This PR adds test coverage for the use of `setTextViaDiff` when formatting the editor's entire buffer. It should resolve #105 and #215.
BTW, I tested the `setTextViaDiff` change on a few large files and I'm seeing a huge speed improvement. For example, edits to https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js on my machine went from taking over 6 seconds to save to less than 1 second.
> test(executePrettier): Add test for setTextViaDiff usage

- dist/config-schema.json
- src/config-schema.json
> fix(config-schema): add `text.md` to default markdown scopes

- dist/main.js
- src/main.js
In some cases, the IndieLinter was `null` when it shouldn't have been. This was due to setting it
null when changing TextEditor objects, which was unnecessary and should not have been done. This
stops doing that so that there is always and IndieLinter available and thus we are always able to
properly set linter messages.
fix #318, #298, #235
> fix(linter): resolve issue with linter not showing error messages properly

- dist/executePrettier/executePrettierOnBufferRange.js
- dist/formatOnSave/index.js
- src/executePrettier/executePrettierOnBufferRange.js
- src/executePrettier/executePrettierOnBufferRange.test.js
- src/formatOnSave/index.js
- src/formatOnSave/index.test.js
We were determining whether or not to use setTextViaDiff (more performant) versus the normal
setTextInBufferRange (less performant but allows replacing only a subset of text in a file if
desired) by whether or not the buffer range of the file equaled the buffer range of the text to be
transformed. However, in some cases such as when the editor automatically inserts an ending newline,
these two ranges can become unequal and we revert to using setTextInBufferRange. This is less
performant and not really necessary. The fix is to just pass an option when calling
`executePrettierOnBufferRange` from `formatOnSave`.
> fix(set-text-via-diff): base use on option instead of flaky buffer range comparison

- package.json
- yarn.lock
We are experiencing interrupted behavior due to regressions in prettier-eslint. We are locking the
bundled version down to a known good configuration.
> fix(prettier-eslint): lock to 8.6.2 to avoid regression

- package.json
- yarn.lock
Some users were saying that we needed to rollback even further to 8.4.0
> fix(prettier-eslint): lock version to 8.4.0

- dist/executePrettier/executePrettierOnBufferRange.js
- src/executePrettier/executePrettierOnBufferRange.js
- src/executePrettier/executePrettierOnBufferRange.test.js
Turn `formatWithCursor` support into a Progressive Enhancement feature until it stabilizes for all supported parsers.
Works as a temporary fix for #361
> fix(executePrettier): fallback to `format` when `formatWithCursor` fails

- .eslintrc.yml
- dist/executePrettier/executePrettierOnBufferRange.js
- src/executePrettier/executePrettierOnBufferRange.js
A lack of type coverage lead to an accidental bug. Added type coverage to prevent this from happening again. 👍 
fixes #364
> fix(executePrettier): adjust for API inconsistencies + add type coverage

- dist/atomInterface/index.js
- dist/main.js
- src/atomInterface/index.js
- src/executePrettier/executePrettierOnBufferRange.js
- src/formatOnSave/index.test.js
- src/main.js
Fix an issue where saving css files required another manual save action
after autoformatting due to stylelint's async api.
- ensure the promise chain stays in tact starting from main.js
'onWillSave' through executePrettierOnBufferRange.js.
> fix: Fix asynchronous saves

- .gitignore
- dist/formatOnSave/shouldFormatOnSave.js
- src/editorInterface/index.js
- src/formatOnSave/isFilePathEslintIgnored.js
- src/formatOnSave/shouldFormatOnSave.js
- src/formatOnSave/shouldFormatOnSave.test.js
- check "shouldRespectEslintignore" setting prior to checking whether
the filepath should be eslintignore'd
- add tests for
: should respect and is eslintignored
: should not respect and is eslintignored
: is not eslintignored
fixes #347
> Fix formatOnSave bug with eslintignore

- dist/displayDebugInfo/index.js
- dist/helpers/getPrettierInstance.js
- dist/helpers/getPrettierPath.js
- package-scripts.yml
- package.json
- src/displayDebugInfo/__snapshots__/index.test.js.snap
- src/displayDebugInfo/index.js
- src/displayDebugInfo/index.test.js
- src/helpers/getPrettierInstance.js
- src/helpers/getPrettierInstance.test.js
- src/helpers/getPrettierPath.js
- yarn.lock
The PR partially addresses https://github.com/prettier/prettier-atom/issues/395
The extension now searches for a globally installed prettier if a local one is not found; it falls back to a a bundled instance only if both attempts have failed. This change makes it possible to use [Prettier plugins](https://prettier.io/docs/en/plugins.html) when someone does not want to have any npm modules locally. Please note that Prettier still has issues with [detecting plugins in global installs](https://github.com/prettier/prettier/issues/4000), but I hope it gets fixed soon. IMO it's OK to merge this PR before that happens and simply `npm i -g prettier` once the upstream fix arrives.
cc @olsonpm
> Fallback to global instance of prettier before falling back to a bundled one

- styles/statusTile.less
Currently prettier-atom is using a hardcoded green color that doesn't follow the success(green) color variable that's documented in Atom's UI styleguide (which is set but the currently used UI theme).
There are 2 ways to use this color, passed as prop via the Less variable or via the `text-success` class.
You should also utilise the Octicons provided from the styleguide instead of the hardcoded `content: ' ✓';` value which you can find in the same file.
_you can view the Styleguidw page by typing Ctrl + Shift + Cmd + G_.
> Follow the UI theme's green color

- .babelrc
- dist/atomInterface/index.js
- dist/displayDebugInfo/index.js
- dist/editorInterface/index.js
- dist/executePrettier/buildPrettierOptions.js
- dist/executePrettier/executePrettierOnBufferRange.js
- dist/executePrettier/executePrettierOnEmbeddedScripts.js
- dist/executePrettier/handleError.js
- dist/executePrettier/index.js
- dist/formatOnSave/index.js
- dist/formatOnSave/isFilePathEslintIgnored.js
- dist/formatOnSave/isFilePathPrettierIgnored.js
- dist/formatOnSave/isPrettierInPackageJson.js
- dist/formatOnSave/shouldFormatOnSave.js
- dist/helpers/atomRelated.js
- dist/helpers/general.js
- dist/helpers/getPrettierInstance.js
- dist/helpers/getPrettierPath.js
- dist/helpers/index.js
- dist/linterInterface/index.js
- dist/main.js
- dist/manualFormat/index.js
- dist/statusTile/createStatusTile.js
- dist/statusTile/getFormatOnSaveStatus.js
- dist/statusTile/index.js
- dist/statusTile/tooltip.js
- dist/statusTile/updateStatusTile.js
- dist/statusTile/updateStatusTileScope.js
- dist/warnAboutLinterEslintFixOnSave/index.js
`babel-preset-env` tells babels your target environment so it can selectively apply polyfills and transforms.
`prettier-atom` has an `env` section in its `.babelrc`, but it is misconfigured.
**Before (Broken)**
```json
{
"presets": [["env", { "electron": 1.4 }], "stage-2"],
"plugins": ["transform-flow-strip-types", "transform-runtime"]
}
```
**After (Fixed)**
```json
{
"presets": [["env", { "targets": { "electron": "1.4" } }], "stage-2"],
"plugins": ["transform-flow-strip-types", "transform-runtime"]
}
```
In the previous version, the `targets` section was missing and the `electron` version was declared as a Float, which cannot be parsed.
This PR fixes the env to use the [correct api](https://github.com/babel/babel-preset-env/blob/master/test/fixtures/preset-options/electron/options.json). …
> Fix usage of babel-preset-env

- dist/config-schema.json
- src/config-schema.json
There was some confusion about the proper syntax for glob patterns as there actually is more than
one type out there. We use the .gitignore style syntax, so this documentation was added.
Resolves #408
> docs(config): add info about .gitignore style pattern syntax

- dist/helpers/isFileFormattable.js
- src/helpers/isFileFormattable.js
- src/helpers/isFileFormattable.test.js
PR #404 changed to using Prettier's `getFileInfo` and `resolveConfig` functions to determine
whether a file is formattable. We were not correctly invoking the API for `getFileInfo` so every
file was coming up as not ignored.
Fixes #446
> fix(prettierignore): properly ignore files again

- dist/atomInterface/index.js
- src/atomInterface/index.js
- src/atomInterface/index.test.js
`atom.project.relativizePath` returns an absolute path when no Atom project can be determined (such
as when editing your Atom config file and many other cases). The `ignore` package will then
hard-error because it is now very strict about getting only relative paths (they assume that the
filenames we are comparing the globs to should be relative to the file in which the globs live, but
we actually hold the globs in the prettier-atom options so this concept doesn't really apply so we
just arbitrarily choose to make relativize paths from the project's root dir). To fix, we relativize
to the parent dir of the file, which is somewhat arbitrary but should be fine.
Fixes #473
> fix: ensure we always pass a relative path to `ignore` pkg

- package.json
Using the latest version of atom (1.34.0 at this time), this package is consistently the slowest to activate. I've recorded the average activation time for this package in two scenarios;
1. A window with one project open and reloaded 4 times: average activation time is 321ms
2. A window with no project open and reloaded 4 times: average activation time is 222ms
Using this activation hook, atom will defer activating this package until the window is ready to use and then there's no impact to startup time. Since this package doesn't need to do heavy setup, I think it should wait as long as possible to activate anyway.
> defer activating the package until the window is loaded.

- package.json
- yarn.lock
In order to support the `nps changelog` command, you need conventional-changelog-cli.
> build(package-dev): add conventional-changelog-cli

- dist/main.js
- src/main.js
After further profiling of the `activate` function, I realized it still took ~300ms, which is alright when it's deferred. After removing the lazy loading wrappers and combining those `subscriptions.add` calls into one, I shaved off >100ms, which is further improvement.
`loadPackageDeps` is the bottleneck now. It's accounting for over 100ms while the rest of the activation is about 15ms.
Is the linter package a hard dependency? I'd suggest deferring the check for it until after activation or during the `initialize` phase of the package because the service consumption happens whenever the providing package is activated. So prettier-atom can activate independently, and a user can install linter much later on and automatically see the messages from this package.
> Cleanup of lazy loading code

- dist/helpers/isFileFormattable.js
- src/helpers/isFileFormattable.js
This is really embarrassing, but my PR #498 broke ignores instead of fixing them. It appeared to fix it on my side, however I'm now retesting from master; it's definitely broken and reverting my change definitely fixes it. Something might've been wrong with my dev env or .prettierignore, either way I goofed somehow. Sorry for the trouble! 😅
> fix(prettierignore): Revert mistake with path passed to prettier.getFileInfo

- dist/displayDebugInfo/index.js
- dist/displayDebugInfo/index.test.js
- src/displayDebugInfo/index.js
- src/displayDebugInfo/index.test.js
BC break on read-pkg-up@6, renamed { pkg: ...} to { package: ...}
https://github.com/sindresorhus/read-pkg-up/releases/tag/v6.0.0
fixes #508
> fix(debug): read-pkg-up@6 renamed pkg to package

- dist/helpers/getPrettierPath.js
- package.json
- src/helpers/getPrettierPath.js
Closes #448 
When Prettier is not found in the current project, the extension first attempts to find a global instance of it and finally falls back to the built-in instance. The second step is important for those who want to use Prettier with plugins, but does not want to see local `node_modules` in each project just because of it. Searching for global Prettier was added in https://github.com/prettier/prettier-atom/pull/397 by me; we use this feature in [litvis](https://github.com/gicentre/litvis#automatic-code-formatting).
Recently, my colleague @jwoLondon discovered that global Prettier does not get resolved when Node and NPM are installed via [NVM](https://github.com/nvm-sh/nvm). This setup method is pretty prevalent and is especially helpful when a user does not have admin rights …
> fix(global-prettier-resolution): add fallback for NVM users

- dist/atomInterface/index.js
- dist/config-schema.json
- dist/executePrettier/executePrettierOnBufferRange.js
- dist/executePrettier/executePrettierOnBufferRange.test.js
- src/atomInterface/index.js
- src/config-schema.json
- src/executePrettier/executePrettierOnBufferRange.js
- src/executePrettier/executePrettierOnBufferRange.test.js
Add an option to use configuration from `.editorconfig`, enabled by default.
BREAKING CHANGE: If the user has a `.editorconfig` file, with `max_line_length` then that value will
be used instead of Prettier's `printWidth`. This is the default behaviour of prettier when run on
the command line, but was not the default behaviour of prettier-atom (but it should be, and now is)
#514
> feat: Add option to use configuration from `.editorconfig`

- package.json
- yarn.lock
Using a temporary fork for prettier-eslint due to maintainer having been unresponsive. Feels
warranted as this is a showstopping bug affecting many users.
Fork uses the changes in this PR: https://github.com/prettier/prettier-eslint/pull/242
Implemented using yarn's alias feature: https://yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add-alias
fix #505
> fix: Use fork of prettier-eslint with cwd fix

- dist/formatOnSave/isPrettierInPackageJson.js
- dist/formatOnSave/isPrettierInPackageJson.test.js
- src/formatOnSave/isPrettierInPackageJson.js
- src/formatOnSave/isPrettierInPackageJson.test.js
A new issue just like #510. 
read-pkg-up in the new version renames a key from package to packageJson:
<details>
Only format if Prettier in dependencies does not work.
Search terms: isDisabledIfNotInPackageJson #43 formatOnSave
</details>
> fix(deps): correctly use new pkg-up, fixup 898ea715, #734
